name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Add dependencies about external libraries
      run: |
        pip install pyqt5
        printf "[MASTER]\n" > ~/.pylintrc
        printf "extension-pkg-whitelist=PyQt5\n" >> ~/.pylintrc
        printf "[BASIC]\n" >> ~/.pylintrc
        printf "attr-rgx=_?_?(?:(?:[a-z0-9]+(?:_[a-z0-9]+)*_?_?)|(?:[a-z0-9]+(?:[A-Z][a-z0-9]*)*))$\n" >> ~/.pylintrc
        printf "method-rgx=_?_?(?:(?:[a-z0-9]+(?:_[a-z0-9]+)*_?_?)|(?:[a-z0-9]+(?:[A-Z][a-z0-9]*)*))$\n" >> ~/.pylintrc
        printf "variable-rgx=_?_?(?:(?:[a-z0-9]+(?:_[a-z0-9]+)*_?_?)|(?:[a-z0-9]+(?:[A-Z][a-z0-9]*)*))$\n" >> ~/.pylintrc
    - name: Analyze the code with pylint
      run: |
        pylint $(git ls-files '*.py')
